Wrong errors arguments
InvalidPhpizeError and UnsupportedPhpApiError don't use name attribute. UnsupportedPhpApiError can't be raisen because it needs the name parameter.

See error in https://github.com/Homebrew/homebrew-php/pull/1379

```
Error: wrong number of arguments (0 for 1)
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php-extension.rb:7:in `initialize'
/usr/local/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php-extension.rb:38:in `new'
/usr/local/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php-extension.rb:38:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:50:in `new'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:28:in `install'
/usr/local/Library/brew.rb:136:in `<main>'
```

Signed-off-by: Jack Nagel <jacknagel@gmail.com>